<?php

class FormularioPoms {

    /**
     *  Adjetivos do poms.
     */
    static function adjetivos() {
        return array(
            1=>'amistoso',
            2=>'tenso',
            3=>'bravo',
            4=>'esgotado',
            5=>'infeliz',
            6=>'sereno',
            7=>'animado',
            8=>'confuso',
            9=>'arrependido',
            10=>'agitado',
            11=>'apático',
            12=>'mau humurado',
            13=>'preocupado com os outros',
            14=>'triste',
            15=>'ativo',
            16=>'aponto de explodir',
            17=>'resmungão',
            18=>'abatido',
            19=>'energético',
            20=>'apavorado',            
            21=>'sem esperança',
            22=>'relaxado',
            23=>'desvalorizado',
            24=>'rancoroso',
            25=>'simpático',
            26=>'intranquilo',
            27=>'inquieto',
            28=>'incapaz de concentrar-se',
            29=>'cansado',
            30=>'cooperador',
            31=>'irritado',
            32=>'desanimado',
            33=>'ressentido',
            34=>'nervoso',
            35=>'sozinho',
            36=>'miserável',
            37=>'atordoado',
            38=>'alegre',
            39=>'amargurado',
            40=>'exausto',
            41=>'ansioso',
            42=>'briguento',
            43=>'bondoso',
            44=>'deprimido',
            45=>'desesperado',
            46=>'preguiçoso',
            47=>'rebelde',
            48=>'abandonado',
            49=>'aborrecido',
            50=>'desorientado',
            51=>'alerta',
            52=>'decepcionado',
            53=>'furioso',
            54=>'eficiente',
            55=>'confiante',
            56=>'cheio de energia',
            57=>'genioso',
            58=>'inútil',
            59=>'esquecido',
            60=>'sem preocupação',
            61=>'aterrorizado',
            62=>'culpado',
            63=>'rigoroso',
            64=>'inseguro',
            65=>'fatigado'
        );
    }
}
